---
all:
  hosts:
    media-server:
      ansible_host: "<MEDIA_SERVER_TAILSCALE_IP>"
      ansible_user: "<YOUR_USERNAME>"

    ubuntu-server:
      ansible_host: "<UBUNTU_SERVER_TAILSCALE_IP>"
      ansible_user: "<YOUR_USERNAME>"

  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_python_interpreter: /usr/bin/python3
